# Ejercicios de probabilidad

In [111]:
import numpy as np

## Ejercicio 1 

Dos dados se lanzan una vez y se observa el total obtenido. Usa una simulación para encontrar la probabilidad estimada de que la puntuación sea mayor a 7 o un número par. Una simulación es una repetición del mismo experimento multiples veces para observar su comportamiento:

- Ejecuta el experimento 1000 veces (lanza 2 dados 1000 veces, y suma el número de ambos dados).
- Lleva ua cuenta de los números y las veces que la suma fue mayor a 7 o un número par.
- Divide el número del paso 2 entre el número de iteraciones(1000).

### Hacemos una lista con las tiradas
>Hacemos una variable que contenga el numero de tiradas (throws) y hacemos una lista con con las tiradas de dados sumando en ella dos arrays de numpy generados con randint de numpy con numeros entre 1 y 6 ya que son las opciones de un dado convencional y con tamaño throws, luego muestro por pantalla las sumas


In [112]:
throws = 1000
dices = np.random.randint(1, 7, size = throws) + np.random.randint(1, 7, size = throws)
dices

array([ 9,  7,  5,  8,  7,  9,  4,  7,  6,  7,  6, 10,  7,  6,  7,  7,  6,
        8,  5,  7,  8,  8,  9,  5,  6,  9,  6,  6,  7,  6,  6,  5,  5, 11,
        6,  5,  4,  8,  6,  4, 12,  8,  5,  6, 10,  7,  7, 12,  8,  5,  9,
        3,  7,  8,  9,  8,  9,  9,  4,  9,  5,  9, 10, 10, 10,  9,  8,  6,
        5,  8,  4,  5,  6,  7, 12,  5, 10, 11, 10,  5, 11,  4,  4, 10,  6,
       10,  4,  4,  6,  6,  7,  4, 10,  7,  5,  9,  7,  4,  7,  3,  4, 11,
        9,  8,  9,  8,  4,  6, 10,  4,  6,  4,  7,  7,  5,  6,  3,  7, 10,
       10, 10,  8,  5,  9,  8,  9,  7,  5,  5,  7,  7,  5,  5, 10,  8,  8,
        5,  8,  8,  3,  2, 11,  7,  9,  8, 11, 11,  2,  5,  5,  5,  7,  6,
       12,  6,  6,  7,  7,  9,  4,  6,  7, 10, 10,  5,  8,  5,  7,  3,  8,
        9,  6,  3,  4,  6, 11,  5,  9,  7, 10,  8,  7,  4,  5,  8,  9,  8,
       10, 10,  4,  6, 10,  3,  6,  6,  5,  6, 12,  9,  7,  2,  4,  8,  9,
        8, 10,  6,  6, 10,  8,  3,  6,  5,  5,  7,  4,  6, 10,  5,  7,  4,
        7,  8,  7,  7,  6

### Contamos los casos que cumplen las caracteristicas
>Hacemos una variable llamada count que contiene la suma de los casos que o bien el número de la lista es mayor a 7 o bien este es par, utilizamos logical_or de numpy porque no permite usar el or dentro de sum de numpy y quiero que me de valido cuando se da al menos una de las condiciones. Finalmente lo convertimos a entero ya que si no se queda como un entero de numpy en vez de uno de python y queda mejor al imprimirse por pantalla a mi gusto

In [113]:
count = int(np.sum(np.logical_or(dices > 7, dices %2 == 0)))
count

659

### Dividimos entre el numero de tiradas para ver la probabilidad
> Dividimos las variables count del anterior con la throws del inicio para obtener la probabilidad

In [114]:
probability = count / throws
probability

0.659

## Ejercicio 2

Una caja contiene 10 bolas blancas, 20 bolas rojas y 30 bolas verdes. Si tomamos 5 bolas de la caja reemplazándolas (tomando una bola, anotando el color y luego regresandola a la caja). Queremos saber la probabilidad de:

1. Tomar 3 blancas y 2 rojas.
2. Toas todas del mismo color.

Ejecuta el experimento 1000 veces y calcula las probabilidades que mencionadas.

In [115]:
ball_box = {}

# Crea la cajas con las bolas
for i in range(60):
    if i < 10:
        ball_box[i] = "White"
    elif (i > 9) and (i < 30):
        ball_box[i] = "Red"
    else:
        ball_box[i] = "Green"

ball_box

{0: 'White',
 1: 'White',
 2: 'White',
 3: 'White',
 4: 'White',
 5: 'White',
 6: 'White',
 7: 'White',
 8: 'White',
 9: 'White',
 10: 'Red',
 11: 'Red',
 12: 'Red',
 13: 'Red',
 14: 'Red',
 15: 'Red',
 16: 'Red',
 17: 'Red',
 18: 'Red',
 19: 'Red',
 20: 'Red',
 21: 'Red',
 22: 'Red',
 23: 'Red',
 24: 'Red',
 25: 'Red',
 26: 'Red',
 27: 'Red',
 28: 'Red',
 29: 'Red',
 30: 'Green',
 31: 'Green',
 32: 'Green',
 33: 'Green',
 34: 'Green',
 35: 'Green',
 36: 'Green',
 37: 'Green',
 38: 'Green',
 39: 'Green',
 40: 'Green',
 41: 'Green',
 42: 'Green',
 43: 'Green',
 44: 'Green',
 45: 'Green',
 46: 'Green',
 47: 'Green',
 48: 'Green',
 49: 'Green',
 50: 'Green',
 51: 'Green',
 52: 'Green',
 53: 'Green',
 54: 'Green',
 55: 'Green',
 56: 'Green',
 57: 'Green',
 58: 'Green',
 59: 'Green'}

### Iniciamos el número de rondas y el número de bolas por ronda
>Creo las variables rounds y ball_round que nos dan las rondas y las bolas por ronda respectivamente

In [116]:
rounds = 1000
balls_round = 5

### Hacemos el experimento de sacar 5 bolas aleatorias cada ronda durante 1000 de estas
>Utilizamos randint de numpy para obtener una matriz con tantas filas como rondas y columnas como bolas por columna que contenga números entre 0 y 59 ya que los valores de las bolas se encuentran entre estos y al haber reemplazo cada bola sacada no se ve afectada por las anteriores

In [117]:
balls = np.random.randint(0, 60, size=(rounds, balls_round))
balls

array([[ 8, 49, 30, 27, 17],
       [53, 47, 46, 20,  4],
       [36, 13, 38, 57, 32],
       ...,
       [33, 18, 44, 27, 56],
       [49, 21,  0,  2, 16],
       [16, 19, 33, 13, 44]], shape=(1000, 5))

### Hacemos listas que cuenten cuantas bolas hay por color en cada ronda
>Con las mismas condiciones que se utilizan cuando se asignan colores a las bolas hacemos listas que contengan el numero de bolas por color por lista mediante sum de numpy añadiendo también el axis = 1 para que me lo de por filas en especifico

>En el caso del rojo utilizo como en el ejercicio anterior logical_or de numpy en este caso logical_and para suplir un and logico entre las dos condiciones ya que quiero que se cumplan a la vez


In [118]:
white = np.sum(balls < 10, axis = 1)
red = np.sum(np.logical_and(balls > 9, balls < 30), axis = 1)
green = np.sum(balls > 29, axis = 1)
white, red, green

(array([1, 1, 0, 2, 0, 0, 1, 0, 2, 2, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 2, 1,
        1, 2, 0, 1, 1, 0, 0, 0, 1, 1, 2, 0, 1, 1, 2, 0, 1, 0, 0, 3, 2, 1,
        1, 0, 2, 1, 0, 0, 2, 2, 1, 2, 1, 0, 3, 1, 1, 1, 1, 0, 2, 2, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 3, 0, 0, 0, 1, 1, 3,
        1, 1, 1, 0, 0, 1, 0, 0, 0, 2, 1, 1, 2, 0, 2, 1, 0, 0, 3, 2, 1, 0,
        0, 0, 3, 1, 0, 0, 1, 0, 0, 0, 1, 3, 0, 1, 2, 1, 3, 1, 1, 0, 0, 0,
        1, 0, 2, 1, 0, 0, 1, 1, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 1, 0,
        1, 0, 0, 1, 1, 1, 0, 2, 2, 1, 4, 2, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
        1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 3, 0, 2,
        0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 2, 1,
        0, 1, 2, 1, 0, 2, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 2, 0, 0,
        1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 2, 0, 1, 0,
        0, 0, 1, 1, 0, 0, 0, 1, 2, 1, 0, 1, 1, 3, 0, 0, 0, 0, 1, 2, 0, 0,
        1, 1, 0, 0, 0, 0, 2, 1, 1, 1, 

### Comprobamos las conciciones gracias a las anteriores listas
>Asignamos a las variables test_1 y test_2 las veces que se cumple lo que se pide en el ejercicio. El primer test se comprueba con el logical_and anteriormente mencionado y las condiciones de que haya 3 bolas blancas y 2 rojas y luego se cuentan en test_1. El segundo test se comprueba con el logical_or también mencionado en anteriores apartados del proyecto y las condiciones de que haya 5 bolas blancas 5 rojas o 5 verdes, comprobando de esta manera que sean las 5 iguales para despues contarse en test_2.

In [119]:
test_1 = int(np.sum(np.logical_and(white == 3, red == 2)))
test_2 = int(np.sum(np.logical_or(white == 5, red == 5, green == 5)))

test_1, test_2

(6, 7)

### Con los test calculamos la probabilidad
>Calculamos las probabilidades dividiendo los tests por el numero de rondas

In [120]:
probability_1 = test_1 / rounds
probability_2 = test_2 / rounds
probability_1, probability_2

(0.006, 0.007)